baseURL = "https://bortox.it/contribuisci-cs"
languageCode = "it"
defaultContentLanguage = "it"

title = "Fai una donazione"
copyright = "Utilizzerò queste donazioni per sostenere i costi del **server** e del **nome di dominio**, oltre al mio lavoro. Altrimenti, invece di soldi puoi sempre inviare una critica costruttiva per **migliorare il sito web** a bort0x@tuta.io! "

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Fai una donazione sicura :lock: a bortox.it"
  image = "bortox-it.png"  # path relative to static directory

  links = [
    { stripe = { href= "https://donate.stripe.com/dR69BB66G13t7yo000", text = "Offrimi una schiacciata" }},
    { stripe = { href= "https://donate.stripe.com/9AQ3dd0MmeUj2e4001", text = "Scegli quanto donare" }},
    { paypal = { href= "https://paypal.me/bort0x", text = "PayPal" }},
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = {href = "https://github.com/bortox/", text = "Source Code" }},
    # { gitlab = "https://gitlab.com/username" },
    #{ google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { email = { href = "mailto:bortox@bortox.it" , text = "Email" }},
    # { mastodon = "https://mastodon-instance/username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
    { exit = {href="https://bortox.it/", text="Torna su bortox.it"}},
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
    

